/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as BurnConvertContractJson } from "../BurnConvert.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace BurnConvertTypes {
  export type Fields = {
    tokenIdBurn: HexString;
    tokenIdConvert: HexString;
    balanceConvert: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    deposit: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    burnAndConvert: {
      params: CallContractParams<{ amountToBurn: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    deposit: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    burnAndConvert: {
      params: SignExecuteContractMethodParams<{ amountToBurn: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  BurnConvertInstance,
  BurnConvertTypes.Fields
> {
  encodeFields(fields: BurnConvertTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  consts = { ErrorCodes: { NotEnoughFundsContract: BigInt("0") } };

  at(address: string): BurnConvertInstance {
    return new BurnConvertInstance(address);
  }

  tests = {
    deposit: async (
      params: TestContractParamsWithoutMaps<
        BurnConvertTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    burnAndConvert: async (
      params: TestContractParamsWithoutMaps<
        BurnConvertTypes.Fields,
        { amountToBurn: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burnAndConvert", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: BurnConvertTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const BurnConvert = new Factory(
  Contract.fromJson(
    BurnConvertContractJson,
    "",
    "3a7a6e9c64b4a2f04e340a44d28d200fe3515372c2b81f65fb504edfd41572a1",
    []
  )
);
registerContract(BurnConvert);

// Use this class to interact with the blockchain
export class BurnConvertInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BurnConvertTypes.State> {
    return fetchContractState(BurnConvert, this);
  }

  view = {
    deposit: async (
      params: BurnConvertTypes.CallMethodParams<"deposit">
    ): Promise<BurnConvertTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        BurnConvert,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    burnAndConvert: async (
      params: BurnConvertTypes.CallMethodParams<"burnAndConvert">
    ): Promise<BurnConvertTypes.CallMethodResult<"burnAndConvert">> => {
      return callMethod(
        BurnConvert,
        this,
        "burnAndConvert",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    deposit: async (
      params: BurnConvertTypes.SignExecuteMethodParams<"deposit">
    ): Promise<BurnConvertTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(BurnConvert, this, "deposit", params);
    },
    burnAndConvert: async (
      params: BurnConvertTypes.SignExecuteMethodParams<"burnAndConvert">
    ): Promise<BurnConvertTypes.SignExecuteMethodResult<"burnAndConvert">> => {
      return signExecuteMethod(BurnConvert, this, "burnAndConvert", params);
    },
  };
}
